# Generated by Django 3.1.1 on 2020-09-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='用户密码')),
                ('email', models.CharField(blank=True, default='', max_length=255, verbose_name='邮箱')),
                ('tel', models.CharField(max_length=11, verbose_name='手机号')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'tb_user',
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='is_hot',
            field=models.BooleanField(default=False, verbose_name='是否热门'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='no',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='编号'),
        ),
    ]
